CREATE TABLE IF NOT EXISTS "Sponsor" (
  "id" TEXT NOT NULL,
  "companyName" TEXT NOT NULL,
  "contactPerson" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "website" TEXT,
  "businessType" TEXT NOT NULL,
  "package" TEXT NOT NULL,
  "targetProvinces" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "marketingGoal" TEXT NOT NULL DEFAULT '',
  "logoUrl" TEXT,
  "bannerUrls" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "brief" TEXT,
  "status" TEXT NOT NULL DEFAULT 'PENDING',
  "monthlyFee" DECIMAL(65,30),
  "notes" TEXT,
  "approvedBy" TEXT,
  "approvedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Sponsor_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Sponsor_email_key" UNIQUE ("email")
);
